"""Static seed data for dishes (no image_url — fetched live by seed.py via Foodish API)."""

DISHES = [{'category': 'Pizza',
  'description': 'Classic tomato, mozzarella, and fresh basil.',
  'details': {'allergens': 'Dairy',
              'calories': 461,
              'ingredients': 'Classic tomato, mozzarella, and fresh basil.',
              'prep_time_minutes': 12},
  'is_available': True,
  'name': 'Margherita Pizza',
  'price': 12.43,
  'rating': 3.8,
  'tag': 'Bestseller'},
 {'category': 'Pizza',
  'description': 'Loaded with spicy pepperoni and mozzarella.',
  'details': {'allergens': 'Gluten',
              'calories': 269,
              'ingredients': 'Loaded with spicy pepperoni and mozzarella.',
              'prep_time_minutes': 23},
  'is_available': True,
  'name': 'Pepperoni Pizza',
  'price': 12.89,
  'rating': 4.9,
  'tag': 'Gluten-Free'},
 {'category': 'Pizza',
  'description': 'Grilled chicken, red onion, and smoky BBQ sauce.',
  'details': {'allergens': 'Fish',
              'calories': 796,
              'ingredients': 'Grilled chicken, red onion, and smoky BBQ sauce.',
              'prep_time_minutes': 5},
  'is_available': True,
  'name': 'BBQ Chicken Pizza',
  'price': 5.66,
  'rating': 4.1,
  'tag': 'Refreshing'},
 {'category': 'Pizza',
  'description': 'Mozzarella, gorgonzola, parmesan, and fontina.',
  'details': {'allergens': 'Peanuts, Dairy',
              'calories': 186,
              'ingredients': 'Mozzarella, gorgonzola, parmesan, and fontina.',
              'prep_time_minutes': 10},
  'is_available': True,
  'name': 'Four Cheese Pizza',
  'price': 7.23,
  'rating': 4.5,
  'tag': 'Gluten-Free'},
 {'category': 'Pizza',
  'description': 'Wild mushrooms with truffle oil and fontina.',
  'details': {'allergens': 'Sesame',
              'calories': 284,
              'ingredients': 'Wild mushrooms with truffle oil and fontina.',
              'prep_time_minutes': 7},
  'is_available': True,
  'name': 'Mushroom Truffle Pizza',
  'price': 7.17,
  'rating': 4.7,
  'tag': 'Gluten-Free'},
 {'category': 'Pizza',
  'description': 'Ham, pineapple, and mozzarella.',
  'details': {'allergens': 'Fish',
              'calories': 224,
              'ingredients': 'Ham, pineapple, and mozzarella.',
              'prep_time_minutes': 19},
  'is_available': True,
  'name': 'Hawaiian Pizza',
  'price': 15.01,
  'rating': 4.5,
  'tag': 'Refreshing'},
 {'category': 'Pizza',
  'description': 'Bell peppers, olives, onion, and mushroom.',
  'details': {'allergens': 'Dairy',
              'calories': 823,
              'ingredients': 'Bell peppers, olives, onion, and mushroom.',
              'prep_time_minutes': 24},
  'is_available': True,
  'name': 'Veggie Supreme Pizza',
  'price': 5.48,
  'rating': 4.2,
  'tag': 'High Protein'},
 {'category': 'Salads',
  'description': 'Grilled chicken, romaine, parmesan, Caesar dressing.',
  'details': {'allergens': 'Fish',
              'calories': 476,
              'ingredients': 'Grilled chicken, romaine, parmesan, Caesar dressing.',
              'prep_time_minutes': 7},
  'is_available': True,
  'name': 'Chicken Caesar Salad',
  'price': 5.07,
  'rating': 4.1,
  'tag': 'Bestseller'},
 {'category': 'Salads',
  'description': 'Cucumber, tomato, olives, feta, and red onion.',
  'details': {'allergens': 'Shellfish, Sesame',
              'calories': 553,
              'ingredients': 'Cucumber, tomato, olives, feta, and red onion.',
              'prep_time_minutes': 10},
  'is_available': True,
  'name': 'Greek Salad',
  'price': 7.95,
  'rating': 4.6,
  'tag': 'High Protein'},
 {'category': 'Salads',
  'description': 'Kale, quinoa, cranberries, and lemon vinaigrette.',
  'details': {'allergens': 'Shellfish',
              'calories': 843,
              'ingredients': 'Kale, quinoa, cranberries, and lemon vinaigrette.',
              'prep_time_minutes': 7},
  'is_available': True,
  'name': 'Quinoa Kale Salad',
  'price': 7.81,
  'rating': 4.9,
  'tag': 'New'},
 {'category': 'Salads',
  'description': 'Chicken, bacon, egg, avocado, blue cheese.',
  'details': {'allergens': 'Gluten, Dairy',
              'calories': 835,
              'ingredients': 'Chicken, bacon, egg, avocado, blue cheese.',
              'prep_time_minutes': 22},
  'is_available': True,
  'name': 'Cobb Salad',
  'price': 6.53,
  'rating': 4.3,
  'tag': 'Bestseller'},
 {'category': 'Salads',
  'description': 'Sliced beef, herbs, and spicy lime dressing.',
  'details': {'allergens': 'Sesame',
              'calories': 590,
              'ingredients': 'Sliced beef, herbs, and spicy lime dressing.',
              'prep_time_minutes': 13},
  'is_available': True,
  'name': 'Thai Beef Salad',
  'price': 14.69,
  'rating': 4.8,
  'tag': 'Vegan'},
 {'category': 'Salads',
  'description': 'Tomato, mozzarella, basil, balsamic glaze.',
  'details': {'allergens': 'Egg, Dairy',
              'calories': 838,
              'ingredients': 'Tomato, mozzarella, basil, balsamic glaze.',
              'prep_time_minutes': 19},
  'is_available': True,
  'name': 'Caprese Salad',
  'price': 7.14,
  'rating': 4.4,
  'tag': 'Signature'},
 {'category': 'Wraps',
  'description': 'Grilled vegetables, hummus, and feta.',
  'details': {'allergens': 'Sesame, Dairy',
              'calories': 944,
              'ingredients': 'Grilled vegetables, hummus, and feta.',
              'prep_time_minutes': 23},
  'is_available': True,
  'name': 'Veggie Wrap',
  'price': 13.74,
  'rating': 4.4,
  'tag': 'Gluten-Free'},
 {'category': 'Wraps',
  'description': 'Crispy falafel, tahini, pickles, and greens.',
  'details': {'allergens': 'Egg',
              'calories': 685,
              'ingredients': 'Crispy falafel, tahini, pickles, and greens.',
              'prep_time_minutes': 7},
  'is_available': True,
  'name': 'Falafel Wrap',
  'price': 16.87,
  'rating': 4.0,
  'tag': 'Vegetarian'},
 {'category': 'Wraps',
  'description': 'Spiced chicken, garlic sauce, pickled turnip.',
  'details': {'allergens': 'Fish, Peanuts',
              'calories': 612,
              'ingredients': 'Spiced chicken, garlic sauce, pickled turnip.',
              'prep_time_minutes': 24},
  'is_available': True,
  'name': 'Chicken Shawarma Wrap',
  'price': 12.28,
  'rating': 4.8,
  'tag': 'Vegan'},
 {'category': 'Wraps',
  'description': 'Crispy chicken, buffalo sauce, ranch, lettuce.',
  'details': {'allergens': 'Peanuts',
              'calories': 746,
              'ingredients': 'Crispy chicken, buffalo sauce, ranch, lettuce.',
              'prep_time_minutes': 5},
  'is_available': True,
  'name': 'Buffalo Chicken Wrap',
  'price': 16.85,
  'rating': 4.4,
  'tag': 'Comfort Food'},
 {'category': 'Wraps',
  'description': 'Bacon, lettuce, tomato, and mayo.',
  'details': {'allergens': 'Gluten, Sesame',
              'calories': 480,
              'ingredients': 'Bacon, lettuce, tomato, and mayo.',
              'prep_time_minutes': 18},
  'is_available': True,
  'name': 'BLT Wrap',
  'price': 14.03,
  'rating': 4.2,
  'tag': 'Signature'},
 {'category': 'Burgers',
  'description': 'Angus beef patty, cheddar, lettuce, tomato, house sauce.',
  'details': {'allergens': 'Peanuts',
              'calories': 692,
              'ingredients': 'Angus beef patty, cheddar, lettuce, tomato, house sauce.',
              'prep_time_minutes': 10},
  'is_available': True,
  'name': 'Beef Burger',
  'price': 15.36,
  'rating': 4.1,
  'tag': 'Refreshing'},
 {'category': 'Burgers',
  'description': 'Buttermilk fried chicken, slaw, spicy mayo.',
  'details': {'allergens': 'Gluten',
              'calories': 383,
              'ingredients': 'Buttermilk fried chicken, slaw, spicy mayo.',
              'prep_time_minutes': 9},
  'is_available': True,
  'name': 'Crispy Chicken Burger',
  'price': 14.94,
  'rating': 4.4,
  'tag': 'High Protein'},
 {'category': 'Burgers',
  'description': 'Beef patty, sauteed mushrooms, swiss cheese.',
  'details': {'allergens': 'Gluten',
              'calories': 294,
              'ingredients': 'Beef patty, sauteed mushrooms, swiss cheese.',
              'prep_time_minutes': 16},
  'is_available': True,
  'name': 'Mushroom Swiss Burger',
  'price': 11.93,
  'rating': 4.4,
  'tag': 'Spicy'},
 {'category': 'Burgers',
  'description': 'Black bean patty, avocado, chipotle mayo.',
  'details': {'allergens': 'Egg',
              'calories': 260,
              'ingredients': 'Black bean patty, avocado, chipotle mayo.',
              'prep_time_minutes': 7},
  'is_available': True,
  'name': 'Veggie Black Bean Burger',
  'price': 7.49,
  'rating': 4.5,
  'tag': 'Sweet'},
 {'category': 'Burgers',
  'description': 'Two patties, bacon, double cheddar.',
  'details': {'allergens': 'Shellfish, Peanuts',
              'calories': 742,
              'ingredients': 'Two patties, bacon, double cheddar.',
              'prep_time_minutes': 10},
  'is_available': True,
  'name': 'Double Bacon Cheeseburger',
  'price': 6.09,
  'rating': 4.4,
  'tag': 'Spicy'},
 {'category': 'Asian',
  'description': 'Stir-fried rice noodles with shrimp, egg, peanuts.',
  'details': {'allergens': 'None, Peanuts',
              'calories': 910,
              'ingredients': 'Stir-fried rice noodles with shrimp, egg, peanuts.',
              'prep_time_minutes': 14},
  'is_available': True,
  'name': 'Pad Thai',
  'price': 13.87,
  'rating': 4.6,
  'tag': 'Gluten-Free'},
 {'category': 'Asian',
  'description': 'Crispy chicken cutlet with Japanese curry and rice.',
  'details': {'allergens': 'Shellfish',
              'calories': 245,
              'ingredients': 'Crispy chicken cutlet with Japanese curry and rice.',
              'prep_time_minutes': 15},
  'is_available': True,
  'name': 'Chicken Katsu Curry',
  'price': 10.1,
  'rating': 4.1,
  'tag': 'Vegetarian'},
 {'category': 'Asian',
  'description': 'Crispy rolls with cabbage, carrot, glass noodles.',
  'details': {'allergens': 'Sesame',
              'calories': 240,
              'ingredients': 'Crispy rolls with cabbage, carrot, glass noodles.',
              'prep_time_minutes': 12},
  'is_available': True,
  'name': 'Vegetable Spring Rolls',
  'price': 4.59,
  'rating': 4.6,
  'tag': 'Vegan'},
 {'category': 'Asian',
  'description': 'Vietnamese noodle soup with beef and fresh herbs.',
  'details': {'allergens': 'None',
              'calories': 865,
              'ingredients': 'Vietnamese noodle soup with beef and fresh herbs.',
              'prep_time_minutes': 20},
  'is_available': True,
  'name': 'Beef Pho',
  'price': 5.38,
  'rating': 4.1,
  'tag': 'Bestseller'},
 {'category': 'Asian',
  'description': 'Wok-fried chicken with peanuts and chili.',
  'details': {'allergens': 'Fish',
              'calories': 596,
              'ingredients': 'Wok-fried chicken with peanuts and chili.',
              'prep_time_minutes': 11},
  'is_available': True,
  'name': 'Kung Pao Chicken',
  'price': 7.51,
  'rating': 4.4,
  'tag': 'Vegan'},
 {'category': 'Asian',
  'description': 'Wok-fried rice with mixed vegetables.',
  'details': {'allergens': 'Gluten',
              'calories': 926,
              'ingredients': 'Wok-fried rice with mixed vegetables.',
              'prep_time_minutes': 6},
  'is_available': True,
  'name': 'Vegetable Fried Rice',
  'price': 8.89,
  'rating': 4.3,
  'tag': 'Comfort Food'},
 {'category': 'Asian',
  'description': 'Grilled chicken, teriyaki glaze, steamed rice.',
  'details': {'allergens': 'None',
              'calories': 291,
              'ingredients': 'Grilled chicken, teriyaki glaze, steamed rice.',
              'prep_time_minutes': 12},
  'is_available': True,
  'name': 'Chicken Teriyaki Bowl',
  'price': 9.49,
  'rating': 4.2,
  'tag': 'Bestseller'},
 {'category': 'Asian',
  'description': 'Steamed pork and chive dumplings.',
  'details': {'allergens': 'Dairy, Gluten',
              'calories': 653,
              'ingredients': 'Steamed pork and chive dumplings.',
              'prep_time_minutes': 12},
  'is_available': True,
  'name': 'Dumplings',
  'price': 6.24,
  'rating': 4.0,
  'tag': 'Vegan'},
 {'category': 'Italian',
  'description': 'Creamy arborio rice with wild mushrooms and parmesan.',
  'details': {'allergens': 'Fish',
              'calories': 195,
              'ingredients': 'Creamy arborio rice with wild mushrooms and parmesan.',
              'prep_time_minutes': 7},
  'is_available': True,
  'name': 'Wild Mushroom Risotto',
  'price': 12.59,
  'rating': 4.4,
  'tag': 'Bestseller'},
 {'category': 'Italian',
  'description': 'Classic pasta with pancetta, egg, and pecorino.',
  'details': {'allergens': 'Gluten, Shellfish',
              'calories': 590,
              'ingredients': 'Classic pasta with pancetta, egg, and pecorino.',
              'prep_time_minutes': 6},
  'is_available': True,
  'name': 'Spaghetti Carbonara',
  'price': 10.52,
  'rating': 4.1,
  'tag': 'Signature'},
 {'category': 'Italian',
  'description': 'Layered pasta with beef ragu and bechamel.',
  'details': {'allergens': 'Egg, Dairy',
              'calories': 645,
              'ingredients': 'Layered pasta with beef ragu and bechamel.',
              'prep_time_minutes': 14},
  'is_available': True,
  'name': 'Lasagna Bolognese',
  'price': 7.79,
  'rating': 4.7,
  'tag': 'Gluten-Free'},
 {'category': 'Italian',
  'description': 'Spicy tomato sauce with garlic and chili.',
  'details': {'allergens': 'Gluten, None',
              'calories': 773,
              'ingredients': 'Spicy tomato sauce with garlic and chili.',
              'prep_time_minutes': 22},
  'is_available': True,
  'name': 'Penne Arrabbiata',
  'price': 8.18,
  'rating': 5.0,
  'tag': 'Vegetarian'},
 {'category': 'Italian',
  'description': 'Creamy parmesan sauce over fettuccine.',
  'details': {'allergens': 'Egg',
              'calories': 723,
              'ingredients': 'Creamy parmesan sauce over fettuccine.',
              'prep_time_minutes': 10},
  'is_available': True,
  'name': 'Fettuccine Alfredo',
  'price': 11.74,
  'rating': 4.4,
  'tag': 'Vegetarian'},
 {'category': 'Italian',
  'description': 'Potato gnocchi with basil pesto.',
  'details': {'allergens': 'Gluten',
              'calories': 420,
              'ingredients': 'Potato gnocchi with basil pesto.',
              'prep_time_minutes': 17},
  'is_available': True,
  'name': 'Gnocchi al Pesto',
  'price': 5.35,
  'rating': 3.9,
  'tag': 'Vegan'},
 {'category': 'Indian',
  'description': 'Tender chicken in a creamy tomato curry, served with naan.',
  'details': {'allergens': 'Peanuts, Dairy',
              'calories': 777,
              'ingredients': 'Tender chicken in a creamy tomato curry, served with naan.',
              'prep_time_minutes': 23},
  'is_available': True,
  'name': 'Butter Chicken',
  'price': 12.18,
  'rating': 4.3,
  'tag': 'Refreshing'},
 {'category': 'Indian',
  'description': 'Spiced chickpea curry with fresh coriander.',
  'details': {'allergens': 'None, Egg',
              'calories': 451,
              'ingredients': 'Spiced chickpea curry with fresh coriander.',
              'prep_time_minutes': 17},
  'is_available': True,
  'name': 'Chana Masala',
  'price': 12.8,
  'rating': 4.2,
  'tag': 'Signature'},
 {'category': 'Indian',
  'description': 'Slow-cooked lamb in a spiced curry sauce.',
  'details': {'allergens': 'Dairy',
              'calories': 189,
              'ingredients': 'Slow-cooked lamb in a spiced curry sauce.',
              'prep_time_minutes': 19},
  'is_available': True,
  'name': 'Lamb Rogan Josh',
  'price': 16.02,
  'rating': 4.9,
  'tag': 'New'},
 {'category': 'Indian',
  'description': 'Grilled paneer in a creamy spiced tomato sauce.',
  'details': {'allergens': 'Sesame',
              'calories': 315,
              'ingredients': 'Grilled paneer in a creamy spiced tomato sauce.',
              'prep_time_minutes': 16},
  'is_available': True,
  'name': 'Paneer Tikka Masala',
  'price': 11.17,
  'rating': 4.4,
  'tag': 'Vegan'},
 {'category': 'Indian',
  'description': 'Fragrant basmati rice layered with spiced chicken.',
  'details': {'allergens': 'Peanuts',
              'calories': 736,
              'ingredients': 'Fragrant basmati rice layered with spiced chicken.',
              'prep_time_minutes': 14},
  'is_available': True,
  'name': 'Chicken Biryani',
  'price': 8.03,
  'rating': 4.3,
  'tag': 'New'},
 {'category': 'Indian',
  'description': 'Paneer cubes in a creamy spinach curry.',
  'details': {'allergens': 'Egg',
              'calories': 317,
              'ingredients': 'Paneer cubes in a creamy spinach curry.',
              'prep_time_minutes': 13},
  'is_available': True,
  'name': 'Palak Paneer',
  'price': 16.05,
  'rating': 3.9,
  'tag': 'Vegan'},
 {'category': 'Mexican',
  'description': 'Grilled fish, cabbage slaw, chipotle crema in corn tortillas.',
  'details': {'allergens': 'None, Egg',
              'calories': 914,
              'ingredients': 'Grilled fish, cabbage slaw, chipotle crema in corn tortillas.',
              'prep_time_minutes': 15},
  'is_available': True,
  'name': 'Fish Tacos',
  'price': 7.88,
  'rating': 4.5,
  'tag': 'Bestseller'},
 {'category': 'Mexican',
  'description': 'Rice, beans, chicken, salsa, and guacamole.',
  'details': {'allergens': 'Gluten, None',
              'calories': 274,
              'ingredients': 'Rice, beans, chicken, salsa, and guacamole.',
              'prep_time_minutes': 25},
  'is_available': True,
  'name': 'Chicken Burrito Bowl',
  'price': 15.73,
  'rating': 4.8,
  'tag': 'Gluten-Free'},
 {'category': 'Mexican',
  'description': 'Melted cheese and seasoned beef in a flour tortilla.',
  'details': {'allergens': 'Gluten, None',
              'calories': 448,
              'ingredients': 'Melted cheese and seasoned beef in a flour tortilla.',
              'prep_time_minutes': 10},
  'is_available': True,
  'name': 'Beef Quesadilla',
  'price': 8.64,
  'rating': 4.0,
  'tag': 'Sweet'},
 {'category': 'Mexican',
  'description': 'Corn tortillas filled with vegetables and cheese.',
  'details': {'allergens': 'Egg, Shellfish',
              'calories': 332,
              'ingredients': 'Corn tortillas filled with vegetables and cheese.',
              'prep_time_minutes': 22},
  'is_available': True,
  'name': 'Veggie Enchiladas',
  'price': 5.43,
  'rating': 4.9,
  'tag': 'Vegetarian'},
 {'category': 'Mexican',
  'description': 'Slow-cooked pork with onion and cilantro.',
  'details': {'allergens': 'Dairy',
              'calories': 220,
              'ingredients': 'Slow-cooked pork with onion and cilantro.',
              'prep_time_minutes': 16},
  'is_available': True,
  'name': 'Carnitas Tacos',
  'price': 6.08,
  'rating': 4.2,
  'tag': 'Bestseller'},
 {'category': 'Seafood',
  'description': 'Pan-seared salmon with lemon butter and seasonal vegetables.',
  'details': {'allergens': 'Egg',
              'calories': 596,
              'ingredients': 'Pan-seared salmon with lemon butter and seasonal vegetables.',
              'prep_time_minutes': 24},
  'is_available': True,
  'name': 'Grilled Salmon',
  'price': 8.89,
  'rating': 4.5,
  'tag': 'Signature'},
 {'category': 'Seafood',
  'description': 'Garlic butter shrimp over linguine.',
  'details': {'allergens': 'Fish, None',
              'calories': 602,
              'ingredients': 'Garlic butter shrimp over linguine.',
              'prep_time_minutes': 5},
  'is_available': True,
  'name': 'Shrimp Scampi',
  'price': 16.6,
  'rating': 4.8,
  'tag': 'Signature'},
 {'category': 'Seafood',
  'description': 'Beer-battered fish with crispy fries.',
  'details': {'allergens': 'Fish',
              'calories': 434,
              'ingredients': 'Beer-battered fish with crispy fries.',
              'prep_time_minutes': 13},
  'is_available': True,
  'name': 'Fish and Chips',
  'price': 12.81,
  'rating': 4.7,
  'tag': 'Signature'},
 {'category': 'Seafood',
  'description': 'Saffron rice with shrimp, mussels, and calamari.',
  'details': {'allergens': 'Peanuts, Fish',
              'calories': 407,
              'ingredients': 'Saffron rice with shrimp, mussels, and calamari.',
              'prep_time_minutes': 11},
  'is_available': True,
  'name': 'Seafood Paella',
  'price': 15.31,
  'rating': 4.8,
  'tag': 'Sweet'},
 {'category': 'Seafood',
  'description': 'Charred prawns with garlic chili oil.',
  'details': {'allergens': 'Peanuts, Fish',
              'calories': 204,
              'ingredients': 'Charred prawns with garlic chili oil.',
              'prep_time_minutes': 11},
  'is_available': True,
  'name': 'Grilled Prawns',
  'price': 14.36,
  'rating': 4.1,
  'tag': 'Gluten-Free'},
 {'category': 'Breakfast',
  'description': 'Smashed avocado, chili flakes, poached egg on sourdough.',
  'details': {'allergens': 'Sesame, Gluten',
              'calories': 539,
              'ingredients': 'Smashed avocado, chili flakes, poached egg on sourdough.',
              'prep_time_minutes': 25},
  'is_available': True,
  'name': 'Avocado Toast',
  'price': 5.36,
  'rating': 4.7,
  'tag': 'Refreshing'},
 {'category': 'Breakfast',
  'description': 'Fluffy pancakes with maple syrup and butter.',
  'details': {'allergens': 'Dairy',
              'calories': 362,
              'ingredients': 'Fluffy pancakes with maple syrup and butter.',
              'prep_time_minutes': 23},
  'is_available': True,
  'name': 'Classic Pancakes',
  'price': 5.93,
  'rating': 5.0,
  'tag': 'Spicy'},
 {'category': 'Breakfast',
  'description': 'Poached eggs, hollandaise, English muffin.',
  'details': {'allergens': 'Fish',
              'calories': 501,
              'ingredients': 'Poached eggs, hollandaise, English muffin.',
              'prep_time_minutes': 18},
  'is_available': True,
  'name': 'Eggs Benedict',
  'price': 11.9,
  'rating': 4.2,
  'tag': 'New'},
 {'category': 'Breakfast',
  'description': 'Scrambled eggs, cheese, potatoes, salsa.',
  'details': {'allergens': 'Sesame',
              'calories': 225,
              'ingredients': 'Scrambled eggs, cheese, potatoes, salsa.',
              'prep_time_minutes': 18},
  'is_available': True,
  'name': 'Breakfast Burrito',
  'price': 15.65,
  'rating': 4.0,
  'tag': 'Vegetarian'},
 {'category': 'Breakfast',
  'description': 'Yogurt, granola, honey, and fresh berries.',
  'details': {'allergens': 'Peanuts',
              'calories': 518,
              'ingredients': 'Yogurt, granola, honey, and fresh berries.',
              'prep_time_minutes': 24},
  'is_available': True,
  'name': 'Granola Bowl',
  'price': 9.85,
  'rating': 4.9,
  'tag': 'High Protein'},
 {'category': 'Desserts',
  'description': 'Warm chocolate cake with a molten center.',
  'details': {'allergens': 'Shellfish',
              'calories': 514,
              'ingredients': 'Warm chocolate cake with a molten center.',
              'prep_time_minutes': 17},
  'is_available': True,
  'name': 'Chocolate Lava Cake',
  'price': 10.79,
  'rating': 4.6,
  'tag': 'Spicy'},
 {'category': 'Desserts',
  'description': 'Creamy cheesecake with a graham cracker crust.',
  'details': {'allergens': 'Fish, Peanuts',
              'calories': 873,
              'ingredients': 'Creamy cheesecake with a graham cracker crust.',
              'prep_time_minutes': 10},
  'is_available': True,
  'name': 'New York Cheesecake',
  'price': 9.71,
  'rating': 4.9,
  'tag': 'New'},
 {'category': 'Desserts',
  'description': 'Espresso-soaked ladyfingers with mascarpone.',
  'details': {'allergens': 'None, Shellfish',
              'calories': 395,
              'ingredients': 'Espresso-soaked ladyfingers with mascarpone.',
              'prep_time_minutes': 18},
  'is_available': True,
  'name': 'Tiramisu',
  'price': 14.84,
  'rating': 4.2,
  'tag': 'New'},
 {'category': 'Desserts',
  'description': 'Warm spiced apples with a crumbly oat topping.',
  'details': {'allergens': 'Peanuts',
              'calories': 664,
              'ingredients': 'Warm spiced apples with a crumbly oat topping.',
              'prep_time_minutes': 10},
  'is_available': True,
  'name': 'Apple Crumble',
  'price': 9.98,
  'rating': 4.1,
  'tag': 'Comfort Food'},
 {'category': 'Desserts',
  'description': 'Vanilla custard with a caramelized sugar crust.',
  'details': {'allergens': 'Shellfish, Fish',
              'calories': 523,
              'ingredients': 'Vanilla custard with a caramelized sugar crust.',
              'prep_time_minutes': 7},
  'is_available': True,
  'name': 'Creme Brulee',
  'price': 10.89,
  'rating': 4.6,
  'tag': 'Bestseller'},
 {'category': 'Desserts',
  'description': 'Crispy fried dough with cinnamon sugar.',
  'details': {'allergens': 'None',
              'calories': 430,
              'ingredients': 'Crispy fried dough with cinnamon sugar.',
              'prep_time_minutes': 20},
  'is_available': True,
  'name': 'Churros',
  'price': 6.97,
  'rating': 3.8,
  'tag': 'New'},
 {'category': 'Drinks',
  'description': 'Ceremonial-grade matcha whisked with cold milk over ice.',
  'details': {'allergens': 'Shellfish, Dairy',
              'calories': 379,
              'ingredients': 'Ceremonial-grade matcha whisked with cold milk over ice.',
              'prep_time_minutes': 17},
  'is_available': True,
  'name': 'Iced Matcha Latte',
  'price': 9.64,
  'rating': 4.6,
  'tag': 'Sweet'},
 {'category': 'Drinks',
  'description': 'Freshly squeezed orange juice.',
  'details': {'allergens': 'Egg',
              'calories': 948,
              'ingredients': 'Freshly squeezed orange juice.',
              'prep_time_minutes': 8},
  'is_available': True,
  'name': 'Fresh Orange Juice',
  'price': 12.64,
  'rating': 3.8,
  'tag': 'Gluten-Free'},
 {'category': 'Drinks',
  'description': 'Blended mango, yogurt, and honey.',
  'details': {'allergens': 'Dairy',
              'calories': 655,
              'ingredients': 'Blended mango, yogurt, and honey.',
              'prep_time_minutes': 6},
  'is_available': True,
  'name': 'Mango Smoothie',
  'price': 14.47,
  'rating': 4.6,
  'tag': 'Refreshing'},
 {'category': 'Drinks',
  'description': 'Slow-steeped cold brew coffee.',
  'details': {'allergens': 'None, Peanuts',
              'calories': 863,
              'ingredients': 'Slow-steeped cold brew coffee.',
              'prep_time_minutes': 21},
  'is_available': True,
  'name': 'Cold Brew Coffee',
  'price': 10.16,
  'rating': 4.8,
  'tag': 'Refreshing'},
 {'category': 'Drinks',
  'description': 'Fresh lemon juice with sparkling water.',
  'details': {'allergens': 'None',
              'calories': 616,
              'ingredients': 'Fresh lemon juice with sparkling water.',
              'prep_time_minutes': 22},
  'is_available': True,
  'name': 'Sparkling Lemonade',
  'price': 14.61,
  'rating': 4.9,
  'tag': 'Sweet'},
 {'category': 'Drinks',
  'description': 'Tart hibiscus tea served over ice.',
  'details': {'allergens': 'Shellfish, Egg',
              'calories': 832,
              'ingredients': 'Tart hibiscus tea served over ice.',
              'prep_time_minutes': 13},
  'is_available': True,
  'name': 'Hibiscus Iced Tea',
  'price': 10.08,
  'rating': 4.7,
  'tag': 'Refreshing'},
 {'category': 'Mediterranean',
  'description': 'Spiced chicken, rice, hummus, and salad.',
  'details': {'allergens': 'Dairy, None',
              'calories': 420,
              'ingredients': 'Spiced chicken, rice, hummus, and salad.',
              'prep_time_minutes': 13},
  'is_available': True,
  'name': 'Chicken Shawarma Plate',
  'price': 9.95,
  'rating': 4.7,
  'tag': 'High Protein'},
 {'category': 'Mediterranean',
  'description': 'Grilled spiced lamb skewers with tzatziki.',
  'details': {'allergens': 'Fish, Egg',
              'calories': 336,
              'ingredients': 'Grilled spiced lamb skewers with tzatziki.',
              'prep_time_minutes': 11},
  'is_available': True,
  'name': 'Lamb Kofta',
  'price': 6.37,
  'rating': 4.3,
  'tag': 'Vegan'},
 {'category': 'Mediterranean',
  'description': 'Creamy hummus with warm pita and olive oil.',
  'details': {'allergens': 'Fish',
              'calories': 391,
              'ingredients': 'Creamy hummus with warm pita and olive oil.',
              'prep_time_minutes': 18},
  'is_available': True,
  'name': 'Hummus Platter',
  'price': 11.23,
  'rating': 4.3,
  'tag': 'Gluten-Free'},
 {'category': 'Mediterranean',
  'description': 'Rice-stuffed grape leaves with lemon.',
  'details': {'allergens': 'None',
              'calories': 485,
              'ingredients': 'Rice-stuffed grape leaves with lemon.',
              'prep_time_minutes': 17},
  'is_available': True,
  'name': 'Stuffed Grape Leaves',
  'price': 10.41,
  'rating': 4.9,
  'tag': 'Gluten-Free'},
 {'category': 'Mediterranean',
  'description': 'Charred halloumi with honey and herbs.',
  'details': {'allergens': 'Egg, Fish',
              'calories': 209,
              'ingredients': 'Charred halloumi with honey and herbs.',
              'prep_time_minutes': 17},
  'is_available': True,
  'name': 'Grilled Halloumi',
  'price': 7.22,
  'rating': 4.3,
  'tag': 'High Protein'},
 {'category': 'Soups',
  'description': 'Creamy tomato soup with fresh basil.',
  'details': {'allergens': 'Gluten, None',
              'calories': 817,
              'ingredients': 'Creamy tomato soup with fresh basil.',
              'prep_time_minutes': 22},
  'is_available': True,
  'name': 'Tomato Basil Soup',
  'price': 10.3,
  'rating': 4.0,
  'tag': 'Vegetarian'},
 {'category': 'Soups',
  'description': 'Classic comfort soup with egg noodles.',
  'details': {'allergens': 'Fish, Egg',
              'calories': 652,
              'ingredients': 'Classic comfort soup with egg noodles.',
              'prep_time_minutes': 10},
  'is_available': True,
  'name': 'Chicken Noodle Soup',
  'price': 12.47,
  'rating': 4.0,
  'tag': 'Vegetarian'},
 {'category': 'Soups',
  'description': 'Hearty vegetable and bean soup.',
  'details': {'allergens': 'Dairy, Shellfish',
              'calories': 568,
              'ingredients': 'Hearty vegetable and bean soup.',
              'prep_time_minutes': 13},
  'is_available': True,
  'name': 'Minestrone',
  'price': 7.12,
  'rating': 4.2,
  'tag': 'Gluten-Free'},
 {'category': 'Soups',
  'description': 'Creamy roasted squash soup with sage.',
  'details': {'allergens': 'Gluten',
              'calories': 538,
              'ingredients': 'Creamy roasted squash soup with sage.',
              'prep_time_minutes': 12},
  'is_available': True,
  'name': 'Butternut Squash Soup',
  'price': 4.74,
  'rating': 4.4,
  'tag': 'Comfort Food'},
 {'category': 'Soups',
  'description': 'Caramelized onion soup with melted gruyere.',
  'details': {'allergens': 'Shellfish',
              'calories': 384,
              'ingredients': 'Caramelized onion soup with melted gruyere.',
              'prep_time_minutes': 5},
  'is_available': True,
  'name': 'French Onion Soup',
  'price': 13.85,
  'rating': 4.9,
  'tag': 'New'},
 {'category': 'Sandwiches',
  'description': 'Turkey, bacon, lettuce, tomato, and mayo.',
  'details': {'allergens': 'Sesame, Dairy',
              'calories': 757,
              'ingredients': 'Turkey, bacon, lettuce, tomato, and mayo.',
              'prep_time_minutes': 11},
  'is_available': True,
  'name': 'Club Sandwich',
  'price': 6.07,
  'rating': 4.6,
  'tag': 'Sweet'},
 {'category': 'Sandwiches',
  'description': 'Melted cheddar between buttery toasted bread.',
  'details': {'allergens': 'Dairy, Peanuts',
              'calories': 915,
              'ingredients': 'Melted cheddar between buttery toasted bread.',
              'prep_time_minutes': 8},
  'is_available': True,
  'name': 'Grilled Cheese',
  'price': 12.01,
  'rating': 5.0,
  'tag': 'Signature'},
 {'category': 'Sandwiches',
  'description': 'Sliced steak, onions, and melted cheese.',
  'details': {'allergens': 'Dairy',
              'calories': 873,
              'ingredients': 'Sliced steak, onions, and melted cheese.',
              'prep_time_minutes': 17},
  'is_available': True,
  'name': 'Philly Cheesesteak',
  'price': 4.82,
  'rating': 4.2,
  'tag': 'Gluten-Free'},
 {'category': 'Sandwiches',
  'description': 'Turkey, pesto, mozzarella, pressed panini.',
  'details': {'allergens': 'Gluten',
              'calories': 428,
              'ingredients': 'Turkey, pesto, mozzarella, pressed panini.',
              'prep_time_minutes': 8},
  'is_available': True,
  'name': 'Turkey Pesto Panini',
  'price': 11.84,
  'rating': 4.8,
  'tag': 'Spicy'},
 {'category': 'Sandwiches',
  'description': 'Ham, pork, pickles, mustard, swiss cheese.',
  'details': {'allergens': 'Gluten, Fish',
              'calories': 559,
              'ingredients': 'Ham, pork, pickles, mustard, swiss cheese.',
              'prep_time_minutes': 7},
  'is_available': True,
  'name': 'Cubano Sandwich',
  'price': 8.81,
  'rating': 4.3,
  'tag': 'Refreshing'},
 {'category': 'BBQ',
  'description': 'Slow-smoked pulled pork with tangy BBQ sauce.',
  'details': {'allergens': 'Egg, Shellfish',
              'calories': 623,
              'ingredients': 'Slow-smoked pulled pork with tangy BBQ sauce.',
              'prep_time_minutes': 16},
  'is_available': True,
  'name': 'BBQ Pulled Pork',
  'price': 9.71,
  'rating': 4.4,
  'tag': 'Comfort Food'},
 {'category': 'BBQ',
  'description': 'Tender smoked brisket with house rub.',
  'details': {'allergens': 'None, Shellfish',
              'calories': 846,
              'ingredients': 'Tender smoked brisket with house rub.',
              'prep_time_minutes': 13},
  'is_available': True,
  'name': 'Smoked Beef Brisket',
  'price': 6.68,
  'rating': 4.4,
  'tag': 'New'},
 {'category': 'BBQ',
  'description': 'Fall-off-the-bone ribs glazed with BBQ sauce.',
  'details': {'allergens': 'None, Dairy',
              'calories': 510,
              'ingredients': 'Fall-off-the-bone ribs glazed with BBQ sauce.',
              'prep_time_minutes': 12},
  'is_available': True,
  'name': 'BBQ Ribs',
  'price': 14.74,
  'rating': 4.5,
  'tag': 'Vegan'},
 {'category': 'BBQ',
  'description': 'Charred chicken glazed with smoky BBQ sauce.',
  'details': {'allergens': 'None',
              'calories': 864,
              'ingredients': 'Charred chicken glazed with smoky BBQ sauce.',
              'prep_time_minutes': 17},
  'is_available': True,
  'name': 'Grilled BBQ Chicken',
  'price': 13.81,
  'rating': 4.5,
  'tag': 'High Protein'},
 {'category': 'BBQ',
  'description': 'Sweet buttery cornbread, a BBQ classic side.',
  'details': {'allergens': 'Peanuts, None',
              'calories': 397,
              'ingredients': 'Sweet buttery cornbread, a BBQ classic side.',
              'prep_time_minutes': 16},
  'is_available': True,
  'name': 'Cornbread',
  'price': 15.05,
  'rating': 4.0,
  'tag': 'Spicy'},
 {'category': 'Vegan',
  'description': 'Quinoa, roasted vegetables, tahini dressing.',
  'details': {'allergens': 'Shellfish',
              'calories': 190,
              'ingredients': 'Quinoa, roasted vegetables, tahini dressing.',
              'prep_time_minutes': 21},
  'is_available': True,
  'name': 'Vegan Buddha Bowl',
  'price': 13.19,
  'rating': 4.1,
  'tag': 'Bestseller'},
 {'category': 'Vegan',
  'description': 'Pulled jackfruit with smoky spices and slaw.',
  'details': {'allergens': 'None, Fish',
              'calories': 426,
              'ingredients': 'Pulled jackfruit with smoky spices and slaw.',
              'prep_time_minutes': 20},
  'is_available': True,
  'name': 'Jackfruit Tacos',
  'price': 13.43,
  'rating': 4.4,
  'tag': 'Comfort Food'},
 {'category': 'Vegan',
  'description': 'Spiced lentils topped with mashed potato.',
  'details': {'allergens': 'None, Peanuts',
              'calories': 594,
              'ingredients': 'Spiced lentils topped with mashed potato.',
              'prep_time_minutes': 12},
  'is_available': True,
  'name': "Lentil Shepherd's Pie",
  'price': 4.71,
  'rating': 4.2,
  'tag': 'Spicy'},
 {'category': 'Vegan',
  'description': 'Stir-fried noodles with tofu and greens.',
  'details': {'allergens': 'None, Egg',
              'calories': 943,
              'ingredients': 'Stir-fried noodles with tofu and greens.',
              'prep_time_minutes': 22},
  'is_available': True,
  'name': 'Vegan Pad See Ew',
  'price': 11.08,
  'rating': 4.3,
  'tag': 'High Protein'},
 {'category': 'Vegan',
  'description': 'Coconut chickpea curry with fresh herbs.',
  'details': {'allergens': 'Egg',
              'calories': 918,
              'ingredients': 'Coconut chickpea curry with fresh herbs.',
              'prep_time_minutes': 11},
  'is_available': True,
  'name': 'Chickpea Curry',
  'price': 8.3,
  'rating': 4.1,
  'tag': 'High Protein'},
 {'category': 'Bakery',
  'description': 'Buttery, flaky classic French pastry.',
  'details': {'allergens': 'Dairy, Fish',
              'calories': 463,
              'ingredients': 'Buttery, flaky classic French pastry.',
              'prep_time_minutes': 23},
  'is_available': True,
  'name': 'Croissant',
  'price': 6.88,
  'rating': 4.7,
  'tag': 'Refreshing'},
 {'category': 'Bakery',
  'description': 'Moist muffin packed with blueberries.',
  'details': {'allergens': 'Peanuts',
              'calories': 363,
              'ingredients': 'Moist muffin packed with blueberries.',
              'prep_time_minutes': 14},
  'is_available': True,
  'name': 'Blueberry Muffin',
  'price': 6.91,
  'rating': 4.1,
  'tag': 'Vegetarian'},
 {'category': 'Bakery',
  'description': 'Soft roll swirled with cinnamon and icing.',
  'details': {'allergens': 'Dairy, Fish',
              'calories': 479,
              'ingredients': 'Soft roll swirled with cinnamon and icing.',
              'prep_time_minutes': 9},
  'is_available': True,
  'name': 'Cinnamon Roll',
  'price': 5.06,
  'rating': 3.9,
  'tag': 'Comfort Food'},
 {'category': 'Bakery',
  'description': 'Moist banana bread with walnuts.',
  'details': {'allergens': 'Gluten',
              'calories': 670,
              'ingredients': 'Moist banana bread with walnuts.',
              'prep_time_minutes': 19},
  'is_available': True,
  'name': 'Banana Bread',
  'price': 4.65,
  'rating': 4.1,
  'tag': 'High Protein'},
 {'category': 'Bakery',
  'description': 'Naturally leavened, crusty sourdough bread.',
  'details': {'allergens': 'Dairy, Peanuts',
              'calories': 296,
              'ingredients': 'Naturally leavened, crusty sourdough bread.',
              'prep_time_minutes': 7},
  'is_available': True,
  'name': 'Sourdough Loaf',
  'price': 7.63,
  'rating': 4.8,
  'tag': 'Gluten-Free'}]
