"""
Dish seed data for Cella & Cona.

All dietary flags, spice levels, and tags are derived from actual dish
ingredients — not randomised — so the recommendation engine trains on
coherent signals. Images are fetched live at seed time (see seed.py).
"""

DISHES = [{'name': 'Margherita Pizza',
  'description': 'Classic tomato, mozzarella, and fresh basil on a thin crust.',
  'price': 9.5,
  'category': 'Pizza',
  'cuisine': 'Italian',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian,Bestseller',
  'rating': 4.5,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 780,
              'ingredients': 'Classic tomato, mozzarella, and fresh basil on a thin crust.',
              'allergens': 'Gluten, Dairy',
              'prep_time_minutes': 15}},
 {'name': 'Pepperoni Pizza',
  'description': 'Loaded with spicy pepperoni and melted mozzarella.',
  'price': 11.9,
  'category': 'Pizza',
  'cuisine': 'Italian',
  'tag': 'Bestseller',
  'tags': 'Bestseller',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 3,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 900,
              'ingredients': 'Loaded with spicy pepperoni and melted mozzarella.',
              'allergens': 'Gluten, Dairy',
              'prep_time_minutes': 15}},
 {'name': 'BBQ Chicken Pizza',
  'description': 'Grilled chicken, red onion, and smoky BBQ sauce.',
  'price': 12.5,
  'category': 'Pizza',
  'cuisine': 'Italian',
  'tag': '',
  'tags': '',
  'rating': 3.9,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 870,
              'ingredients': 'Grilled chicken, red onion, and smoky BBQ sauce.',
              'allergens': 'Gluten, Dairy',
              'prep_time_minutes': 16}},
 {'name': 'Four Cheese Pizza',
  'description': 'Mozzarella, gorgonzola, parmesan, and fontina.',
  'price': 12.9,
  'category': 'Pizza',
  'cuisine': 'Italian',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 940,
              'ingredients': 'Mozzarella, gorgonzola, parmesan, and fontina.',
              'allergens': 'Gluten, Dairy',
              'prep_time_minutes': 15}},
 {'name': 'Mushroom Truffle Pizza',
  'description': 'Wild mushrooms with truffle oil and fontina.',
  'price': 13.9,
  'category': 'Pizza',
  'cuisine': 'Italian',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian,Signature',
  'rating': 4.5,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 820,
              'ingredients': 'Wild mushrooms with truffle oil and fontina.',
              'allergens': 'Gluten, Dairy',
              'prep_time_minutes': 17}},
 {'name': 'Diavola Pizza',
  'description': 'Spicy salami, chili flakes, and mozzarella.',
  'price': 12.25,
  'category': 'Pizza',
  'cuisine': 'Italian',
  'tag': 'Spicy',
  'tags': 'Spicy',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 4,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 880,
              'ingredients': 'Spicy salami, chili flakes, and mozzarella.',
              'allergens': 'Gluten, Dairy',
              'prep_time_minutes': 15}},
 {'name': 'Veggie Supreme Pizza',
  'description': 'Bell peppers, olives, red onion, and mushroom.',
  'price': 11.5,
  'category': 'Pizza',
  'cuisine': 'Italian',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 760,
              'ingredients': 'Bell peppers, olives, red onion, and mushroom.',
              'allergens': 'Gluten, Dairy',
              'prep_time_minutes': 16}},
 {'name': 'Chicken Caesar Salad',
  'description': 'Grilled chicken, romaine, parmesan, and Caesar dressing.',
  'price': 8.75,
  'category': 'Salads',
  'cuisine': 'Salads',
  'tag': 'High Protein',
  'tags': 'High Protein',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'light',
  'details': {'calories': 520,
              'ingredients': 'Grilled chicken, romaine, parmesan, and Caesar dressing.',
              'allergens': 'Gluten, Dairy, Egg',
              'prep_time_minutes': 10}},
 {'name': 'Greek Salad',
  'description': 'Cucumber, tomato, olives, feta, and red onion.',
  'price': 7.9,
  'category': 'Salads',
  'cuisine': 'Salads',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'light',
  'details': {'calories': 360,
              'ingredients': 'Cucumber, tomato, olives, feta, and red onion.',
              'allergens': 'Dairy',
              'prep_time_minutes': 8}},
 {'name': 'Quinoa Kale Salad',
  'description': 'Kale, quinoa, cranberries, and lemon vinaigrette.',
  'price': 8.5,
  'category': 'Salads',
  'cuisine': 'Salads',
  'tag': 'Vegan',
  'tags': 'Vegan,Healthy',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': True,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'light',
  'details': {'calories': 410,
              'ingredients': 'Kale, quinoa, cranberries, and lemon vinaigrette.',
              'allergens': 'None',
              'prep_time_minutes': 9}},
 {'name': 'Cobb Salad',
  'description': 'Chicken, bacon, egg, avocado, and blue cheese.',
  'price': 10.5,
  'category': 'Salads',
  'cuisine': 'Salads',
  'tag': 'High Protein',
  'tags': 'High Protein',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'light',
  'details': {'calories': 620,
              'ingredients': 'Chicken, bacon, egg, avocado, and blue cheese.',
              'allergens': 'Dairy, Egg',
              'prep_time_minutes': 11}},
 {'name': 'Thai Beef Salad',
  'description': 'Sliced beef, fresh herbs, and spicy lime dressing.',
  'price': 11.25,
  'category': 'Salads',
  'cuisine': 'Salads',
  'tag': 'Spicy',
  'tags': 'Spicy,High Protein',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 4,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'light',
  'details': {'calories': 480,
              'ingredients': 'Sliced beef, fresh herbs, and spicy lime dressing.',
              'allergens': 'Fish',
              'prep_time_minutes': 12}},
 {'name': 'Caprese Salad',
  'description': 'Tomato, mozzarella, basil, and balsamic glaze.',
  'price': 8.25,
  'category': 'Salads',
  'cuisine': 'Salads',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'light',
  'details': {'calories': 340,
              'ingredients': 'Tomato, mozzarella, basil, and balsamic glaze.',
              'allergens': 'Dairy',
              'prep_time_minutes': 6}},
 {'name': 'Veggie Wrap',
  'description': 'Grilled vegetables, hummus, and feta in a whole wheat wrap.',
  'price': 7.25,
  'category': 'Wraps',
  'cuisine': 'Wraps',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch',
  'temp_affinity': 'light',
  'details': {'calories': 430,
              'ingredients': 'Grilled vegetables, hummus, and feta in a whole wheat wrap.',
              'allergens': 'Gluten, Dairy, Sesame',
              'prep_time_minutes': 8}},
 {'name': 'Falafel Wrap',
  'description': 'Crispy falafel, tahini, pickles, and fresh greens.',
  'price': 7.5,
  'category': 'Wraps',
  'cuisine': 'Wraps',
  'tag': 'Vegan',
  'tags': 'Vegan',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': True,
  'is_vegan': True,
  'is_gluten_free': False,
  'meal_times': 'lunch',
  'temp_affinity': 'light',
  'details': {'calories': 470,
              'ingredients': 'Crispy falafel, tahini, pickles, and fresh greens.',
              'allergens': 'Gluten, Sesame',
              'prep_time_minutes': 10}},
 {'name': 'Chicken Shawarma Wrap',
  'description': 'Spiced chicken, garlic sauce, and pickled turnip.',
  'price': 8.9,
  'category': 'Wraps',
  'cuisine': 'Wraps',
  'tag': 'Bestseller',
  'tags': 'Bestseller',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch',
  'temp_affinity': 'light',
  'details': {'calories': 560,
              'ingredients': 'Spiced chicken, garlic sauce, and pickled turnip.',
              'allergens': 'Gluten, Dairy',
              'prep_time_minutes': 11}},
 {'name': 'Buffalo Chicken Wrap',
  'description': 'Crispy chicken, buffalo sauce, ranch, and lettuce.',
  'price': 8.75,
  'category': 'Wraps',
  'cuisine': 'Wraps',
  'tag': 'Spicy',
  'tags': 'Spicy',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 4,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch',
  'temp_affinity': 'light',
  'details': {'calories': 640,
              'ingredients': 'Crispy chicken, buffalo sauce, ranch, and lettuce.',
              'allergens': 'Gluten, Dairy, Egg',
              'prep_time_minutes': 10}},
 {'name': 'BLT Wrap',
  'description': 'Crispy bacon, lettuce, tomato, and mayo.',
  'price': 7.75,
  'category': 'Wraps',
  'cuisine': 'Wraps',
  'tag': '',
  'tags': '',
  'rating': 3.9,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch',
  'temp_affinity': 'light',
  'details': {'calories': 520,
              'ingredients': 'Crispy bacon, lettuce, tomato, and mayo.',
              'allergens': 'Gluten, Egg',
              'prep_time_minutes': 7}},
 {'name': 'Beef Burger',
  'description': 'Angus beef patty, cheddar, lettuce, tomato, and house sauce.',
  'price': 11.9,
  'category': 'Burgers',
  'cuisine': 'American',
  'tag': 'Signature',
  'tags': 'Signature,Bestseller',
  'rating': 4.5,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 890,
              'ingredients': 'Angus beef patty, cheddar, lettuce, tomato, and house sauce.',
              'allergens': 'Gluten, Dairy, Egg',
              'prep_time_minutes': 12}},
 {'name': 'Crispy Chicken Burger',
  'description': 'Buttermilk fried chicken, slaw, and spicy mayo.',
  'price': 10.75,
  'category': 'Burgers',
  'cuisine': 'American',
  'tag': 'Bestseller',
  'tags': 'Bestseller',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 3,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 820,
              'ingredients': 'Buttermilk fried chicken, slaw, and spicy mayo.',
              'allergens': 'Gluten, Egg',
              'prep_time_minutes': 13}},
 {'name': 'Mushroom Swiss Burger',
  'description': 'Beef patty, sauteed mushrooms, and swiss cheese.',
  'price': 12.5,
  'category': 'Burgers',
  'cuisine': 'American',
  'tag': '',
  'tags': '',
  'rating': 3.9,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 910,
              'ingredients': 'Beef patty, sauteed mushrooms, and swiss cheese.',
              'allergens': 'Gluten, Dairy',
              'prep_time_minutes': 13}},
 {'name': 'Veggie Black Bean Burger',
  'description': 'Black bean patty, avocado, and chipotle mayo.',
  'price': 9.9,
  'category': 'Burgers',
  'cuisine': 'American',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 640,
              'ingredients': 'Black bean patty, avocado, and chipotle mayo.',
              'allergens': 'Gluten, Egg',
              'prep_time_minutes': 12}},
 {'name': 'Double Bacon Cheeseburger',
  'description': 'Two beef patties, bacon, and double cheddar.',
  'price': 14.5,
  'category': 'Burgers',
  'cuisine': 'American',
  'tag': 'Signature',
  'tags': 'Signature',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 1180,
              'ingredients': 'Two beef patties, bacon, and double cheddar.',
              'allergens': 'Gluten, Dairy, Egg',
              'prep_time_minutes': 15}},
 {'name': 'Pad Thai',
  'description': 'Stir-fried rice noodles with shrimp, egg, and tamarind sauce.',
  'price': 10.5,
  'category': 'Asian',
  'cuisine': 'Asian',
  'tag': 'Bestseller',
  'tags': 'Bestseller',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 3,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 610,
              'ingredients': 'Stir-fried rice noodles with shrimp, egg, and tamarind sauce.',
              'allergens': 'Shellfish, Egg, Peanuts',
              'prep_time_minutes': 14}},
 {'name': 'Chicken Katsu Curry',
  'description': 'Crispy chicken cutlet with Japanese curry and rice.',
  'price': 11.25,
  'category': 'Asian',
  'cuisine': 'Asian',
  'tag': 'Bestseller',
  'tags': 'Bestseller',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 780,
              'ingredients': 'Crispy chicken cutlet with Japanese curry and rice.',
              'allergens': 'Gluten, Egg',
              'prep_time_minutes': 16}},
 {'name': 'Vegetable Spring Rolls',
  'description': 'Crispy rolls with cabbage, carrot, and glass noodles.',
  'price': 5.5,
  'category': 'Asian',
  'cuisine': 'Asian',
  'tag': 'Vegan',
  'tags': 'Vegan',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': True,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 280,
              'ingredients': 'Crispy rolls with cabbage, carrot, and glass noodles.',
              'allergens': 'Gluten',
              'prep_time_minutes': 9}},
 {'name': 'Beef Pho',
  'description': 'Vietnamese noodle soup with beef and fresh herbs.',
  'price': 11.9,
  'category': 'Asian',
  'cuisine': 'Asian',
  'tag': 'Comfort Food',
  'tags': 'Comfort Food',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 540,
              'ingredients': 'Vietnamese noodle soup with beef and fresh herbs.',
              'allergens': 'Fish',
              'prep_time_minutes': 18}},
 {'name': 'Kung Pao Chicken',
  'description': 'Wok-fried chicken with peanuts and dried chili.',
  'price': 10.9,
  'category': 'Asian',
  'cuisine': 'Asian',
  'tag': 'Spicy',
  'tags': 'Spicy',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 4,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 660,
              'ingredients': 'Wok-fried chicken with peanuts and dried chili.',
              'allergens': 'Peanuts',
              'prep_time_minutes': 13}},
 {'name': 'Vegetable Fried Rice',
  'description': 'Wok-fried rice with mixed seasonal vegetables.',
  'price': 8.5,
  'category': 'Asian',
  'cuisine': 'Asian',
  'tag': 'Vegan',
  'tags': 'Vegan',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': True,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 520,
              'ingredients': 'Wok-fried rice with mixed seasonal vegetables.',
              'allergens': 'None',
              'prep_time_minutes': 11}},
 {'name': 'Chicken Teriyaki Bowl',
  'description': 'Grilled chicken, teriyaki glaze, and steamed rice.',
  'price': 10.25,
  'category': 'Asian',
  'cuisine': 'Asian',
  'tag': 'High Protein',
  'tags': 'High Protein',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 640,
              'ingredients': 'Grilled chicken, teriyaki glaze, and steamed rice.',
              'allergens': 'Gluten',
              'prep_time_minutes': 12}},
 {'name': 'Pork Dumplings',
  'description': 'Steamed pork and chive dumplings with soy dipping sauce.',
  'price': 7.5,
  'category': 'Asian',
  'cuisine': 'Asian',
  'tag': '',
  'tags': '',
  'rating': 3.9,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 420,
              'ingredients': 'Steamed pork and chive dumplings with soy dipping sauce.',
              'allergens': 'Gluten',
              'prep_time_minutes': 12}},
 {'name': 'Wild Mushroom Risotto',
  'description': 'Creamy arborio rice with wild mushrooms and parmesan.',
  'price': 12.25,
  'category': 'Italian',
  'cuisine': 'Italian',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 640,
              'ingredients': 'Creamy arborio rice with wild mushrooms and parmesan.',
              'allergens': 'Dairy',
              'prep_time_minutes': 20}},
 {'name': 'Spaghetti Carbonara',
  'description': 'Classic pasta with pancetta, egg, and pecorino.',
  'price': 11.5,
  'category': 'Italian',
  'cuisine': 'Italian',
  'tag': 'Signature',
  'tags': 'Signature',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 820,
              'ingredients': 'Classic pasta with pancetta, egg, and pecorino.',
              'allergens': 'Gluten, Dairy, Egg',
              'prep_time_minutes': 15}},
 {'name': 'Lasagna Bolognese',
  'description': 'Layered pasta with slow-cooked beef ragu and bechamel.',
  'price': 12.9,
  'category': 'Italian',
  'cuisine': 'Italian',
  'tag': 'Comfort Food',
  'tags': 'Comfort Food',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 880,
              'ingredients': 'Layered pasta with slow-cooked beef ragu and bechamel.',
              'allergens': 'Gluten, Dairy, Egg',
              'prep_time_minutes': 22}},
 {'name': 'Penne Arrabbiata',
  'description': 'Spicy tomato sauce with garlic and red chili.',
  'price': 9.9,
  'category': 'Italian',
  'cuisine': 'Italian',
  'tag': 'Spicy',
  'tags': 'Spicy,Vegan',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 4,
  'is_vegetarian': True,
  'is_vegan': True,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 610,
              'ingredients': 'Spicy tomato sauce with garlic and red chili.',
              'allergens': 'Gluten',
              'prep_time_minutes': 13}},
 {'name': 'Fettuccine Alfredo',
  'description': 'Rich creamy parmesan sauce over fresh fettuccine.',
  'price': 11.25,
  'category': 'Italian',
  'cuisine': 'Italian',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian,Comfort Food',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 900,
              'ingredients': 'Rich creamy parmesan sauce over fresh fettuccine.',
              'allergens': 'Gluten, Dairy',
              'prep_time_minutes': 14}},
 {'name': 'Gnocchi al Pesto',
  'description': 'Soft potato gnocchi tossed in fresh basil pesto.',
  'price': 10.9,
  'category': 'Italian',
  'cuisine': 'Italian',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 680,
              'ingredients': 'Soft potato gnocchi tossed in fresh basil pesto.',
              'allergens': 'Gluten, Dairy',
              'prep_time_minutes': 14}},
 {'name': 'Butter Chicken',
  'description': 'Tender chicken in a creamy spiced tomato curry with naan.',
  'price': 12.9,
  'category': 'Indian',
  'cuisine': 'Indian',
  'tag': 'Bestseller',
  'tags': 'Bestseller',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 850,
              'ingredients': 'Tender chicken in a creamy spiced tomato curry with naan.',
              'allergens': 'Dairy, Gluten',
              'prep_time_minutes': 18}},
 {'name': 'Chana Masala',
  'description': 'Spiced chickpea curry with fresh coriander.',
  'price': 8.5,
  'category': 'Indian',
  'cuisine': 'Indian',
  'tag': 'Vegan',
  'tags': 'Vegan',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 3,
  'is_vegetarian': True,
  'is_vegan': True,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 480,
              'ingredients': 'Spiced chickpea curry with fresh coriander.',
              'allergens': 'None',
              'prep_time_minutes': 15}},
 {'name': 'Lamb Rogan Josh',
  'description': 'Slow-cooked lamb in an aromatic Kashmiri curry.',
  'price': 14.5,
  'category': 'Indian',
  'cuisine': 'Indian',
  'tag': 'Signature',
  'tags': 'Signature',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 3,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 780,
              'ingredients': 'Slow-cooked lamb in an aromatic Kashmiri curry.',
              'allergens': 'Dairy',
              'prep_time_minutes': 25}},
 {'name': 'Paneer Tikka Masala',
  'description': 'Grilled paneer in a creamy spiced tomato sauce.',
  'price': 11.5,
  'category': 'Indian',
  'cuisine': 'Indian',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 3,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 720,
              'ingredients': 'Grilled paneer in a creamy spiced tomato sauce.',
              'allergens': 'Dairy',
              'prep_time_minutes': 17}},
 {'name': 'Chicken Biryani',
  'description': 'Fragrant basmati rice layered with spiced chicken.',
  'price': 12.25,
  'category': 'Indian',
  'cuisine': 'Indian',
  'tag': 'Bestseller',
  'tags': 'Bestseller',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 3,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 760,
              'ingredients': 'Fragrant basmati rice layered with spiced chicken.',
              'allergens': 'Dairy',
              'prep_time_minutes': 24}},
 {'name': 'Palak Paneer',
  'description': 'Paneer cubes in a creamy spinach curry.',
  'price': 10.9,
  'category': 'Indian',
  'cuisine': 'Indian',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 580,
              'ingredients': 'Paneer cubes in a creamy spinach curry.',
              'allergens': 'Dairy',
              'prep_time_minutes': 16}},
 {'name': 'Vegetable Samosa',
  'description': 'Crispy pastry filled with spiced potato and peas.',
  'price': 5.25,
  'category': 'Indian',
  'cuisine': 'Indian',
  'tag': 'Vegan',
  'tags': 'Vegan',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': True,
  'is_vegan': True,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 320,
              'ingredients': 'Crispy pastry filled with spiced potato and peas.',
              'allergens': 'Gluten',
              'prep_time_minutes': 10}},
 {'name': 'Fish Tacos',
  'description': 'Grilled fish, cabbage slaw, and chipotle crema in corn tortillas.',
  'price': 10.25,
  'category': 'Mexican',
  'cuisine': 'Mexican',
  'tag': 'Gluten-Free',
  'tags': 'Gluten-Free',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 3,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 590,
              'ingredients': 'Grilled fish, cabbage slaw, and chipotle crema in corn tortillas.',
              'allergens': 'Fish, Dairy',
              'prep_time_minutes': 12}},
 {'name': 'Chicken Burrito Bowl',
  'description': 'Rice, black beans, chicken, salsa, and guacamole.',
  'price': 10.9,
  'category': 'Mexican',
  'cuisine': 'Mexican',
  'tag': 'High Protein',
  'tags': 'High Protein',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 720,
              'ingredients': 'Rice, black beans, chicken, salsa, and guacamole.',
              'allergens': 'Dairy',
              'prep_time_minutes': 12}},
 {'name': 'Beef Quesadilla',
  'description': 'Melted cheese and seasoned beef in a grilled flour tortilla.',
  'price': 9.9,
  'category': 'Mexican',
  'cuisine': 'Mexican',
  'tag': '',
  'tags': '',
  'rating': 3.9,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 780,
              'ingredients': 'Melted cheese and seasoned beef in a grilled flour tortilla.',
              'allergens': 'Gluten, Dairy',
              'prep_time_minutes': 11}},
 {'name': 'Veggie Enchiladas',
  'description': 'Corn tortillas filled with vegetables and melted cheese.',
  'price': 9.5,
  'category': 'Mexican',
  'cuisine': 'Mexican',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 640,
              'ingredients': 'Corn tortillas filled with vegetables and melted cheese.',
              'allergens': 'Dairy',
              'prep_time_minutes': 16}},
 {'name': 'Carnitas Tacos',
  'description': 'Slow-cooked pulled pork with onion and cilantro.',
  'price': 10.5,
  'category': 'Mexican',
  'cuisine': 'Mexican',
  'tag': 'Bestseller',
  'tags': 'Bestseller',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 610,
              'ingredients': 'Slow-cooked pulled pork with onion and cilantro.',
              'allergens': 'None',
              'prep_time_minutes': 14}},
 {'name': 'Loaded Nachos',
  'description': 'Tortilla chips with cheese, jalapenos, and sour cream.',
  'price': 8.9,
  'category': 'Mexican',
  'cuisine': 'Mexican',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian,Spicy',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 3,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 840,
              'ingredients': 'Tortilla chips with cheese, jalapenos, and sour cream.',
              'allergens': 'Dairy',
              'prep_time_minutes': 10}},
 {'name': 'Grilled Salmon',
  'description': 'Pan-seared salmon with lemon butter and seasonal vegetables.',
  'price': 14.9,
  'category': 'Seafood',
  'cuisine': 'Seafood',
  'tag': 'High Protein',
  'tags': 'High Protein,Healthy',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'dinner',
  'temp_affinity': 'light',
  'details': {'calories': 610,
              'ingredients': 'Pan-seared salmon with lemon butter and seasonal vegetables.',
              'allergens': 'Fish, Dairy',
              'prep_time_minutes': 18}},
 {'name': 'Shrimp Scampi',
  'description': 'Garlic butter shrimp served over linguine.',
  'price': 13.9,
  'category': 'Seafood',
  'cuisine': 'Seafood',
  'tag': 'Signature',
  'tags': 'Signature',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'dinner',
  'temp_affinity': 'light',
  'details': {'calories': 720,
              'ingredients': 'Garlic butter shrimp served over linguine.',
              'allergens': 'Shellfish, Gluten, Dairy',
              'prep_time_minutes': 16}},
 {'name': 'Fish and Chips',
  'description': 'Beer-battered cod with crispy hand-cut fries.',
  'price': 12.5,
  'category': 'Seafood',
  'cuisine': 'Seafood',
  'tag': 'Comfort Food',
  'tags': 'Comfort Food',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'dinner',
  'temp_affinity': 'light',
  'details': {'calories': 940,
              'ingredients': 'Beer-battered cod with crispy hand-cut fries.',
              'allergens': 'Fish, Gluten',
              'prep_time_minutes': 17}},
 {'name': 'Seafood Paella',
  'description': 'Saffron rice with shrimp, mussels, and calamari.',
  'price': 16.9,
  'category': 'Seafood',
  'cuisine': 'Seafood',
  'tag': 'Signature',
  'tags': 'Signature',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'dinner',
  'temp_affinity': 'light',
  'details': {'calories': 780,
              'ingredients': 'Saffron rice with shrimp, mussels, and calamari.',
              'allergens': 'Shellfish, Fish',
              'prep_time_minutes': 28}},
 {'name': 'Grilled Prawns',
  'description': 'Charred prawns with garlic and chili oil.',
  'price': 15.5,
  'category': 'Seafood',
  'cuisine': 'Seafood',
  'tag': 'High Protein',
  'tags': 'High Protein,Spicy',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 3,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'dinner',
  'temp_affinity': 'light',
  'details': {'calories': 420,
              'ingredients': 'Charred prawns with garlic and chili oil.',
              'allergens': 'Shellfish',
              'prep_time_minutes': 14}},
 {'name': 'Avocado Toast',
  'description': 'Smashed avocado, chili flakes, and poached egg on sourdough.',
  'price': 6.9,
  'category': 'Breakfast',
  'cuisine': 'Breakfast',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian,Healthy',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'breakfast',
  'temp_affinity': 'neutral',
  'details': {'calories': 410,
              'ingredients': 'Smashed avocado, chili flakes, and poached egg on sourdough.',
              'allergens': 'Gluten, Egg',
              'prep_time_minutes': 7}},
 {'name': 'Classic Pancakes',
  'description': 'Fluffy buttermilk pancakes with maple syrup and butter.',
  'price': 7.5,
  'category': 'Breakfast',
  'cuisine': 'Breakfast',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian,Sweet',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'breakfast',
  'temp_affinity': 'neutral',
  'details': {'calories': 680,
              'ingredients': 'Fluffy buttermilk pancakes with maple syrup and butter.',
              'allergens': 'Gluten, Dairy, Egg',
              'prep_time_minutes': 12}},
 {'name': 'Eggs Benedict',
  'description': 'Poached eggs and hollandaise on a toasted English muffin.',
  'price': 9.9,
  'category': 'Breakfast',
  'cuisine': 'Breakfast',
  'tag': 'Bestseller',
  'tags': 'Bestseller',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'breakfast',
  'temp_affinity': 'neutral',
  'details': {'calories': 620,
              'ingredients': 'Poached eggs and hollandaise on a toasted English muffin.',
              'allergens': 'Gluten, Dairy, Egg',
              'prep_time_minutes': 14}},
 {'name': 'Breakfast Burrito',
  'description': 'Scrambled eggs, cheese, potatoes, and salsa in a tortilla.',
  'price': 8.25,
  'category': 'Breakfast',
  'cuisine': 'Breakfast',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'breakfast',
  'temp_affinity': 'neutral',
  'details': {'calories': 700,
              'ingredients': 'Scrambled eggs, cheese, potatoes, and salsa in a tortilla.',
              'allergens': 'Gluten, Dairy, Egg',
              'prep_time_minutes': 11}},
 {'name': 'Granola Yogurt Bowl',
  'description': 'Greek yogurt, house granola, honey, and fresh berries.',
  'price': 6.5,
  'category': 'Breakfast',
  'cuisine': 'Breakfast',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian,Healthy',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'breakfast',
  'temp_affinity': 'neutral',
  'details': {'calories': 380,
              'ingredients': 'Greek yogurt, house granola, honey, and fresh berries.',
              'allergens': 'Dairy, Gluten',
              'prep_time_minutes': 5}},
 {'name': 'Shakshuka',
  'description': 'Eggs poached in a spiced tomato and pepper sauce.',
  'price': 8.9,
  'category': 'Breakfast',
  'cuisine': 'Breakfast',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian,Spicy',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 3,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'breakfast',
  'temp_affinity': 'neutral',
  'details': {'calories': 450,
              'ingredients': 'Eggs poached in a spiced tomato and pepper sauce.',
              'allergens': 'Egg',
              'prep_time_minutes': 16}},
 {'name': 'Chocolate Lava Cake',
  'description': 'Warm chocolate cake with a molten center and vanilla ice cream.',
  'price': 6.5,
  'category': 'Desserts',
  'cuisine': 'Dessert',
  'tag': 'Sweet',
  'tags': 'Sweet,Bestseller',
  'rating': 4.5,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'dinner,snack',
  'temp_affinity': 'neutral',
  'details': {'calories': 520,
              'ingredients': 'Warm chocolate cake with a molten center and vanilla ice cream.',
              'allergens': 'Gluten, Dairy, Egg',
              'prep_time_minutes': 10}},
 {'name': 'New York Cheesecake',
  'description': 'Creamy baked cheesecake on a graham cracker crust.',
  'price': 6.9,
  'category': 'Desserts',
  'cuisine': 'Dessert',
  'tag': 'Sweet',
  'tags': 'Sweet',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'dinner,snack',
  'temp_affinity': 'neutral',
  'details': {'calories': 480,
              'ingredients': 'Creamy baked cheesecake on a graham cracker crust.',
              'allergens': 'Gluten, Dairy, Egg',
              'prep_time_minutes': 8}},
 {'name': 'Tiramisu',
  'description': 'Espresso-soaked ladyfingers layered with mascarpone.',
  'price': 7.25,
  'category': 'Desserts',
  'cuisine': 'Dessert',
  'tag': 'Sweet',
  'tags': 'Sweet,Signature',
  'rating': 4.5,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'dinner,snack',
  'temp_affinity': 'neutral',
  'details': {'calories': 440,
              'ingredients': 'Espresso-soaked ladyfingers layered with mascarpone.',
              'allergens': 'Gluten, Dairy, Egg',
              'prep_time_minutes': 9}},
 {'name': 'Apple Crumble',
  'description': 'Warm spiced apples with a buttery oat crumble topping.',
  'price': 6.25,
  'category': 'Desserts',
  'cuisine': 'Dessert',
  'tag': 'Sweet',
  'tags': 'Sweet,Comfort Food',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'dinner,snack',
  'temp_affinity': 'neutral',
  'details': {'calories': 460,
              'ingredients': 'Warm spiced apples with a buttery oat crumble topping.',
              'allergens': 'Gluten, Dairy',
              'prep_time_minutes': 12}},
 {'name': 'Creme Brulee',
  'description': 'Silky vanilla custard with a caramelized sugar crust.',
  'price': 7.5,
  'category': 'Desserts',
  'cuisine': 'Dessert',
  'tag': 'Sweet',
  'tags': 'Sweet',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'dinner,snack',
  'temp_affinity': 'neutral',
  'details': {'calories': 410,
              'ingredients': 'Silky vanilla custard with a caramelized sugar crust.',
              'allergens': 'Dairy, Egg',
              'prep_time_minutes': 10}},
 {'name': 'Churros',
  'description': 'Crispy fried dough dusted with cinnamon sugar.',
  'price': 5.5,
  'category': 'Desserts',
  'cuisine': 'Dessert',
  'tag': 'Sweet',
  'tags': 'Sweet',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'dinner,snack',
  'temp_affinity': 'neutral',
  'details': {'calories': 490,
              'ingredients': 'Crispy fried dough dusted with cinnamon sugar.',
              'allergens': 'Gluten, Dairy, Egg',
              'prep_time_minutes': 9}},
 {'name': 'Iced Matcha Latte',
  'description': 'Ceremonial-grade matcha whisked with cold milk over ice.',
  'price': 4.75,
  'category': 'Drinks',
  'cuisine': 'Beverage',
  'tag': 'Refreshing',
  'tags': 'Refreshing',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'breakfast,lunch,dinner,snack',
  'temp_affinity': 'light',
  'details': {'calories': 180,
              'ingredients': 'Ceremonial-grade matcha whisked with cold milk over ice.',
              'allergens': 'Dairy',
              'prep_time_minutes': 5}},
 {'name': 'Fresh Orange Juice',
  'description': 'Freshly squeezed seasonal oranges.',
  'price': 4.25,
  'category': 'Drinks',
  'cuisine': 'Beverage',
  'tag': 'Vegan',
  'tags': 'Vegan,Refreshing,Healthy',
  'rating': 4.4,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': True,
  'is_gluten_free': True,
  'meal_times': 'breakfast,lunch,dinner,snack',
  'temp_affinity': 'light',
  'details': {'calories': 120,
              'ingredients': 'Freshly squeezed seasonal oranges.',
              'allergens': 'None',
              'prep_time_minutes': 4}},
 {'name': 'Mango Smoothie',
  'description': 'Blended ripe mango with yogurt and a touch of honey.',
  'price': 5.5,
  'category': 'Drinks',
  'cuisine': 'Beverage',
  'tag': 'Refreshing',
  'tags': 'Refreshing',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'breakfast,lunch,dinner,snack',
  'temp_affinity': 'light',
  'details': {'calories': 260,
              'ingredients': 'Blended ripe mango with yogurt and a touch of honey.',
              'allergens': 'Dairy',
              'prep_time_minutes': 5}},
 {'name': 'Cold Brew Coffee',
  'description': 'Slow-steeped 18-hour cold brew, served black over ice.',
  'price': 4.5,
  'category': 'Drinks',
  'cuisine': 'Beverage',
  'tag': 'Vegan',
  'tags': 'Vegan,Refreshing',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': True,
  'is_gluten_free': True,
  'meal_times': 'breakfast,lunch,dinner,snack',
  'temp_affinity': 'light',
  'details': {'calories': 15,
              'ingredients': 'Slow-steeped 18-hour cold brew, served black over ice.',
              'allergens': 'None',
              'prep_time_minutes': 3}},
 {'name': 'Sparkling Lemonade',
  'description': 'Fresh lemon juice topped with sparkling water.',
  'price': 4.25,
  'category': 'Drinks',
  'cuisine': 'Beverage',
  'tag': 'Vegan',
  'tags': 'Vegan,Refreshing',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': True,
  'is_gluten_free': True,
  'meal_times': 'breakfast,lunch,dinner,snack',
  'temp_affinity': 'light',
  'details': {'calories': 140,
              'ingredients': 'Fresh lemon juice topped with sparkling water.',
              'allergens': 'None',
              'prep_time_minutes': 4}},
 {'name': 'Hibiscus Iced Tea',
  'description': 'Tart hibiscus flowers brewed and served over ice.',
  'price': 4.0,
  'category': 'Drinks',
  'cuisine': 'Beverage',
  'tag': 'Vegan',
  'tags': 'Vegan,Refreshing',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': True,
  'is_gluten_free': True,
  'meal_times': 'breakfast,lunch,dinner,snack',
  'temp_affinity': 'light',
  'details': {'calories': 90,
              'ingredients': 'Tart hibiscus flowers brewed and served over ice.',
              'allergens': 'None',
              'prep_time_minutes': 4}},
 {'name': 'Chicken Shawarma Plate',
  'description': 'Spiced chicken with rice, hummus, and Israeli salad.',
  'price': 12.5,
  'category': 'Mediterranean',
  'cuisine': 'Mediterranean',
  'tag': 'High Protein',
  'tags': 'High Protein,Bestseller',
  'rating': 4.5,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 780,
              'ingredients': 'Spiced chicken with rice, hummus, and Israeli salad.',
              'allergens': 'Sesame',
              'prep_time_minutes': 16}},
 {'name': 'Lamb Kofta',
  'description': 'Grilled spiced lamb skewers served with tzatziki.',
  'price': 13.9,
  'category': 'Mediterranean',
  'cuisine': 'Mediterranean',
  'tag': 'Signature',
  'tags': 'Signature',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 3,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 690,
              'ingredients': 'Grilled spiced lamb skewers served with tzatziki.',
              'allergens': 'Dairy',
              'prep_time_minutes': 18}},
 {'name': 'Hummus Platter',
  'description': "Creamy hummus with warm pita, olive oil, and za'atar.",
  'price': 7.9,
  'category': 'Mediterranean',
  'cuisine': 'Mediterranean',
  'tag': 'Vegan',
  'tags': 'Vegan',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': True,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 480,
              'ingredients': "Creamy hummus with warm pita, olive oil, and za'atar.",
              'allergens': 'Gluten, Sesame',
              'prep_time_minutes': 7}},
 {'name': 'Stuffed Grape Leaves',
  'description': 'Rice-stuffed vine leaves with lemon and olive oil.',
  'price': 6.9,
  'category': 'Mediterranean',
  'cuisine': 'Mediterranean',
  'tag': 'Vegan',
  'tags': 'Vegan',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': True,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 320,
              'ingredients': 'Rice-stuffed vine leaves with lemon and olive oil.',
              'allergens': 'None',
              'prep_time_minutes': 12}},
 {'name': 'Grilled Halloumi',
  'description': 'Charred halloumi drizzled with honey and fresh herbs.',
  'price': 8.5,
  'category': 'Mediterranean',
  'cuisine': 'Mediterranean',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 420,
              'ingredients': 'Charred halloumi drizzled with honey and fresh herbs.',
              'allergens': 'Dairy',
              'prep_time_minutes': 9}},
 {'name': 'Tomato Basil Soup',
  'description': 'Velvety roasted tomato soup finished with fresh basil.',
  'price': 6.5,
  'category': 'Soups',
  'cuisine': 'Soups',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian,Comfort Food',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 240,
              'ingredients': 'Velvety roasted tomato soup finished with fresh basil.',
              'allergens': 'Dairy',
              'prep_time_minutes': 15}},
 {'name': 'Chicken Noodle Soup',
  'description': 'Classic comfort soup with egg noodles and root vegetables.',
  'price': 7.25,
  'category': 'Soups',
  'cuisine': 'Soups',
  'tag': 'Comfort Food',
  'tags': 'Comfort Food',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 320,
              'ingredients': 'Classic comfort soup with egg noodles and root vegetables.',
              'allergens': 'Gluten, Egg',
              'prep_time_minutes': 18}},
 {'name': 'Minestrone',
  'description': 'Hearty Italian vegetable and bean soup.',
  'price': 6.9,
  'category': 'Soups',
  'cuisine': 'Soups',
  'tag': 'Vegan',
  'tags': 'Vegan,Healthy',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': True,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 280,
              'ingredients': 'Hearty Italian vegetable and bean soup.',
              'allergens': 'Gluten',
              'prep_time_minutes': 20}},
 {'name': 'Butternut Squash Soup',
  'description': 'Creamy roasted squash soup with crispy sage.',
  'price': 6.9,
  'category': 'Soups',
  'cuisine': 'Soups',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian,Comfort Food',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 260,
              'ingredients': 'Creamy roasted squash soup with crispy sage.',
              'allergens': 'Dairy',
              'prep_time_minutes': 18}},
 {'name': 'French Onion Soup',
  'description': 'Caramelized onion broth topped with melted gruyere.',
  'price': 7.9,
  'category': 'Soups',
  'cuisine': 'Soups',
  'tag': 'Comfort Food',
  'tags': 'Comfort Food,Signature',
  'rating': 4.5,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 380,
              'ingredients': 'Caramelized onion broth topped with melted gruyere.',
              'allergens': 'Gluten, Dairy',
              'prep_time_minutes': 25}},
 {'name': 'Spicy Lentil Soup',
  'description': 'Red lentils simmered with cumin and harissa.',
  'price': 6.5,
  'category': 'Soups',
  'cuisine': 'Soups',
  'tag': 'Vegan',
  'tags': 'Vegan,Spicy',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 4,
  'is_vegetarian': True,
  'is_vegan': True,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 300,
              'ingredients': 'Red lentils simmered with cumin and harissa.',
              'allergens': 'None',
              'prep_time_minutes': 17}},
 {'name': 'Club Sandwich',
  'description': 'Turkey, bacon, lettuce, tomato, and mayo on toasted bread.',
  'price': 9.5,
  'category': 'Sandwiches',
  'cuisine': 'American',
  'tag': '',
  'tags': '',
  'rating': 3.9,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch',
  'temp_affinity': 'neutral',
  'details': {'calories': 720,
              'ingredients': 'Turkey, bacon, lettuce, tomato, and mayo on toasted bread.',
              'allergens': 'Gluten, Egg',
              'prep_time_minutes': 10}},
 {'name': 'Grilled Cheese',
  'description': 'Melted sharp cheddar between buttery toasted sourdough.',
  'price': 6.9,
  'category': 'Sandwiches',
  'cuisine': 'American',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian,Comfort Food',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch',
  'temp_affinity': 'neutral',
  'details': {'calories': 610,
              'ingredients': 'Melted sharp cheddar between buttery toasted sourdough.',
              'allergens': 'Gluten, Dairy',
              'prep_time_minutes': 8}},
 {'name': 'Philly Cheesesteak',
  'description': 'Thin sliced steak, grilled onions, and melted provolone.',
  'price': 12.25,
  'category': 'Sandwiches',
  'cuisine': 'American',
  'tag': 'Signature',
  'tags': 'Signature',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch',
  'temp_affinity': 'neutral',
  'details': {'calories': 880,
              'ingredients': 'Thin sliced steak, grilled onions, and melted provolone.',
              'allergens': 'Gluten, Dairy',
              'prep_time_minutes': 14}},
 {'name': 'Turkey Pesto Panini',
  'description': 'Turkey, basil pesto, and mozzarella, pressed warm.',
  'price': 9.9,
  'category': 'Sandwiches',
  'cuisine': 'American',
  'tag': '',
  'tags': '',
  'rating': 3.9,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch',
  'temp_affinity': 'neutral',
  'details': {'calories': 640,
              'ingredients': 'Turkey, basil pesto, and mozzarella, pressed warm.',
              'allergens': 'Gluten, Dairy',
              'prep_time_minutes': 10}},
 {'name': 'Cubano Sandwich',
  'description': 'Roast pork, ham, pickles, mustard, and swiss cheese.',
  'price': 10.9,
  'category': 'Sandwiches',
  'cuisine': 'American',
  'tag': 'Signature',
  'tags': 'Signature',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'lunch',
  'temp_affinity': 'neutral',
  'details': {'calories': 780,
              'ingredients': 'Roast pork, ham, pickles, mustard, and swiss cheese.',
              'allergens': 'Gluten, Dairy',
              'prep_time_minutes': 12}},
 {'name': 'BBQ Pulled Pork',
  'description': 'Slow-smoked pulled pork with tangy house BBQ sauce.',
  'price': 12.5,
  'category': 'BBQ',
  'cuisine': 'American',
  'tag': 'Bestseller',
  'tags': 'Bestseller,Comfort Food',
  'rating': 4.5,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 820,
              'ingredients': 'Slow-smoked pulled pork with tangy house BBQ sauce.',
              'allergens': 'Gluten',
              'prep_time_minutes': 20}},
 {'name': 'Smoked Beef Brisket',
  'description': '14-hour smoked brisket with a peppery house rub.',
  'price': 15.9,
  'category': 'BBQ',
  'cuisine': 'American',
  'tag': 'Signature',
  'tags': 'Signature,High Protein',
  'rating': 4.5,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 880,
              'ingredients': '14-hour smoked brisket with a peppery house rub.',
              'allergens': 'None',
              'prep_time_minutes': 25}},
 {'name': 'BBQ Ribs',
  'description': 'Fall-off-the-bone pork ribs glazed in smoky BBQ sauce.',
  'price': 16.5,
  'category': 'BBQ',
  'cuisine': 'American',
  'tag': 'Signature',
  'tags': 'Signature',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 980,
              'ingredients': 'Fall-off-the-bone pork ribs glazed in smoky BBQ sauce.',
              'allergens': 'None',
              'prep_time_minutes': 25}},
 {'name': 'Grilled BBQ Chicken',
  'description': 'Charred half chicken glazed with smoky BBQ sauce.',
  'price': 13.25,
  'category': 'BBQ',
  'cuisine': 'American',
  'tag': 'High Protein',
  'tags': 'High Protein',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': False,
  'is_vegan': False,
  'is_gluten_free': True,
  'meal_times': 'dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 740,
              'ingredients': 'Charred half chicken glazed with smoky BBQ sauce.',
              'allergens': 'None',
              'prep_time_minutes': 22}},
 {'name': 'Buttermilk Cornbread',
  'description': 'Sweet, buttery skillet cornbread — the BBQ classic side.',
  'price': 4.5,
  'category': 'BBQ',
  'cuisine': 'American',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian,Sweet',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'dinner',
  'temp_affinity': 'warm',
  'details': {'calories': 320,
              'ingredients': 'Sweet, buttery skillet cornbread — the BBQ classic side.',
              'allergens': 'Gluten, Dairy, Egg',
              'prep_time_minutes': 15}},
 {'name': 'Vegan Buddha Bowl',
  'description': 'Quinoa, roasted vegetables, chickpeas, and tahini dressing.',
  'price': 10.5,
  'category': 'Vegan',
  'cuisine': 'Vegan',
  'tag': 'Vegan',
  'tags': 'Vegan,Healthy',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': True,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 560,
              'ingredients': 'Quinoa, roasted vegetables, chickpeas, and tahini dressing.',
              'allergens': 'Sesame',
              'prep_time_minutes': 14}},
 {'name': 'Jackfruit Tacos',
  'description': 'Pulled jackfruit with smoky spices, slaw, and lime.',
  'price': 9.9,
  'category': 'Vegan',
  'cuisine': 'Vegan',
  'tag': 'Vegan',
  'tags': 'Vegan,Spicy',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 3,
  'is_vegetarian': True,
  'is_vegan': True,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 480,
              'ingredients': 'Pulled jackfruit with smoky spices, slaw, and lime.',
              'allergens': 'None',
              'prep_time_minutes': 13}},
 {'name': "Lentil Shepherd's Pie",
  'description': 'Spiced lentils and vegetables under fluffy mashed potato.',
  'price': 10.9,
  'category': 'Vegan',
  'cuisine': 'Vegan',
  'tag': 'Vegan',
  'tags': 'Vegan,Comfort Food',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': True,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 620,
              'ingredients': 'Spiced lentils and vegetables under fluffy mashed potato.',
              'allergens': 'None',
              'prep_time_minutes': 25}},
 {'name': 'Vegan Pad See Ew',
  'description': 'Wide rice noodles stir-fried with tofu and Chinese broccoli.',
  'price': 10.25,
  'category': 'Vegan',
  'cuisine': 'Vegan',
  'tag': 'Vegan',
  'tags': 'Vegan',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 2,
  'is_vegetarian': True,
  'is_vegan': True,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 590,
              'ingredients': 'Wide rice noodles stir-fried with tofu and Chinese broccoli.',
              'allergens': 'None',
              'prep_time_minutes': 14}},
 {'name': 'Coconut Chickpea Curry',
  'description': 'Chickpeas simmered in coconut milk with fresh herbs.',
  'price': 9.9,
  'category': 'Vegan',
  'cuisine': 'Vegan',
  'tag': 'Vegan',
  'tags': 'Vegan,Spicy',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 3,
  'is_vegetarian': True,
  'is_vegan': True,
  'is_gluten_free': True,
  'meal_times': 'lunch,dinner',
  'temp_affinity': 'neutral',
  'details': {'calories': 540,
              'ingredients': 'Chickpeas simmered in coconut milk with fresh herbs.',
              'allergens': 'None',
              'prep_time_minutes': 18}},
 {'name': 'Butter Croissant',
  'description': 'Flaky, buttery, laminated French pastry.',
  'price': 3.5,
  'category': 'Bakery',
  'cuisine': 'Bakery',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'breakfast,snack',
  'temp_affinity': 'neutral',
  'details': {'calories': 280,
              'ingredients': 'Flaky, buttery, laminated French pastry.',
              'allergens': 'Gluten, Dairy, Egg',
              'prep_time_minutes': 5}},
 {'name': 'Blueberry Muffin',
  'description': 'Moist muffin packed with fresh blueberries.',
  'price': 3.9,
  'category': 'Bakery',
  'cuisine': 'Bakery',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian,Sweet',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'breakfast,snack',
  'temp_affinity': 'neutral',
  'details': {'calories': 380,
              'ingredients': 'Moist muffin packed with fresh blueberries.',
              'allergens': 'Gluten, Dairy, Egg',
              'prep_time_minutes': 5}},
 {'name': 'Cinnamon Roll',
  'description': 'Soft roll swirled with cinnamon and cream cheese icing.',
  'price': 4.5,
  'category': 'Bakery',
  'cuisine': 'Bakery',
  'tag': 'Sweet',
  'tags': 'Sweet,Bestseller',
  'rating': 4.5,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'breakfast,snack',
  'temp_affinity': 'neutral',
  'details': {'calories': 460,
              'ingredients': 'Soft roll swirled with cinnamon and cream cheese icing.',
              'allergens': 'Gluten, Dairy, Egg',
              'prep_time_minutes': 6}},
 {'name': 'Banana Walnut Bread',
  'description': 'Moist banana bread studded with toasted walnuts.',
  'price': 4.25,
  'category': 'Bakery',
  'cuisine': 'Bakery',
  'tag': 'Vegetarian',
  'tags': 'Vegetarian,Sweet',
  'rating': 4.3,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': False,
  'is_gluten_free': False,
  'meal_times': 'breakfast,snack',
  'temp_affinity': 'neutral',
  'details': {'calories': 410,
              'ingredients': 'Moist banana bread studded with toasted walnuts.',
              'allergens': 'Gluten, Dairy, Egg',
              'prep_time_minutes': 5}},
 {'name': 'Sourdough Loaf',
  'description': 'Naturally leavened, crusty artisan sourdough.',
  'price': 5.5,
  'category': 'Bakery',
  'cuisine': 'Bakery',
  'tag': 'Vegan',
  'tags': 'Vegan',
  'rating': 4.1,
  'is_available': True,
  'spice_level': 1,
  'is_vegetarian': True,
  'is_vegan': True,
  'is_gluten_free': False,
  'meal_times': 'breakfast,snack',
  'temp_affinity': 'neutral',
  'details': {'calories': 240,
              'ingredients': 'Naturally leavened, crusty artisan sourdough.',
              'allergens': 'Gluten',
              'prep_time_minutes': 5}}]
